In [104]:
import pandas as pd
import torch
from scipy.spatial.transform import Rotation

In [2]:
filepath="/home/wanghao/桌面/南岭项目-角色模型/XSENS数据/9.8测试数据-wh-1.8/Xsens DATA/NPose/New Session-001.xlsx"
sheet=pd.read_excel(filepath,sheet_name=None)

In [3]:
sheet.keys()

dict_keys(['General Information', 'Markers', 'Segment Orientation - Quat', 'Segment Orientation - Euler', 'Segment Position', 'Segment Velocity', 'Segment Acceleration', 'Segment Angular Velocity', 'Segment Angular Acceleration', 'Joint Angles ZXY', 'Joint Angles XZY', 'Ergonomic Joint Angles ZXY', 'Ergonomic Joint Angles XZY', 'Center of Mass', 'Sensor Free Acceleration', 'Sensor Magnetic Field', 'Sensor Orientation - Quat', 'Sensor Orientation - Euler'])

In [9]:
sheet['Joint Angles ZXY'].keys()[1:][::3]

Index(['L5S1 Lateral Bending', 'L4L3 Lateral Bending', 'L1T12 Lateral Bending',
       'T9T8 Lateral Bending', 'T1C7 Lateral Bending',
       'C1 Head Lateral Bending', 'Right T4 Shoulder Abduction/Adduction',
       'Right Shoulder Abduction/Adduction',
       'Right Elbow Ulnar Deviation/Radial Deviation',
       'Right Wrist Ulnar Deviation/Radial Deviation',
       'Left T4 Shoulder Abduction/Adduction',
       'Left Shoulder Abduction/Adduction',
       'Left Elbow Ulnar Deviation/Radial Deviation',
       'Left Wrist Ulnar Deviation/Radial Deviation',
       'Right Hip Abduction/Adduction', 'Right Knee Abduction/Adduction',
       'Right Ankle Abduction/Adduction',
       'Right Ball Foot Abduction/Adduction', 'Left Hip Abduction/Adduction',
       'Left Knee Abduction/Adduction', 'Left Ankle Abduction/Adduction',
       'Left Ball Foot Abduction/Adduction'],
      dtype='object')

In [10]:
angles_xzy=sheet['Joint Angles XZY']
angles_zxy=sheet['Joint Angles ZXY']

In [13]:
angles_xzy.keys()

Index(['Frame', 'L5S1 Lateral Bending', 'L5S1 Axial Bending',
       'L5S1 Flexion/Extension', 'L4L3 Lateral Bending', 'L4L3 Axial Rotation',
       'L4L3 Flexion/Extension', 'L1T12 Lateral Bending',
       'L1T12 Axial Rotation', 'L1T12 Flexion/Extension',
       'T9T8 Lateral Bending', 'T9T8 Axial Rotation', 'T9T8 Flexion/Extension',
       'T1C7 Lateral Bending', 'T1C7 Axial Rotation', 'T1C7 Flexion/Extension',
       'C1 Head Lateral Bending', 'C1 Head Axial Rotation',
       'C1 Head Flexion/Extension', 'Right T4 Shoulder Abduction/Adduction',
       'Right T4 Shoulder Internal/External Rotation',
       'Right T4 Shoulder Flexion/Extension',
       'Right Shoulder Abduction/Adduction',
       'Right Shoulder Internal/External Rotation',
       'Right Shoulder Flexion/Extension',
       'Right Elbow Ulnar Deviation/Radial Deviation',
       'Right Elbow Pronation/Supination', 'Right Elbow Flexion/Extension',
       'Right Wrist Ulnar Deviation/Radial Deviation',
       'Right Wris

In [14]:
angles_xzy-angles_zxy

Frame  L5S1 Lateral Bending  L5S1 Axial Bending  L5S1 Flexion/Extension  \
0         0              0.057536           -1.230369               -0.139137   
1         0              0.057897           -1.227359               -0.137290   
2         0              0.058267           -1.224379               -0.135458   
3         0              0.058583           -1.221757               -0.133892   
4         0              0.058920           -1.220753               -0.132818   
...     ...                   ...                 ...                     ...   
1872      0             -0.001395            0.063348               -0.000795   
1873      0             -0.001284            0.062975               -0.000848   
1874      0             -0.001153            0.061700               -0.000889   
1875      0             -0.001011            0.059620               -0.000914   
1876      0             -0.000850            0.056108               -0.000906   

      L4L3 Lateral Bending  L4L3 Axial Rotation  L4L3 Flexion/Extension  \
0                 0.009915             0.335176                0.016515   
1                 0.009706             0.329883                0.016087   
2                 0.009496             0.324590                0.015664   
3                 0.009323             0.320193                0.015316   
4                 0.009190             0.316893                0.015062   
...                    ...                  ...                     ...   
1872             -0.002096            -0.051029                0.000276   
1873             -0.002330            -0.055741                0.000324   
1874             -0.002581            -0.060643                0.000376   
1875             -0.002843            -0.065626                0.000433   
1876             -0.003105            -0.070386                0.000489   

      L1T12 Lateral Bending  L1T12 Axial Rotation  L1T12 Flexion/Extension  \
0                  0.004983             -0.237549                -0.011705   
1                  0.005010             -0.236952                -0.011555   
2                  0.005037             -0.236362                -0.011406   
3                  0.005060             -0.235845                -0.011281   
4                  0.005084             -0.235642                -0.011200   
...                     ...                   ...                      ...   
1872              -0.000118              0.012082                -0.000065   
1873              -0.000108              0.012007                -0.000070   
1874              -0.000097              0.011749                -0.000073   
1875              -0.000085              0.011339                -0.000075   
1876              -0.000071              0.010663                -0.000074   

      ...  Left Hip Flexion/Extension  Left Knee Abduction/Adduction  \
0     ...                   -2.434853                      -0.049634   
1     ...                   -2.360869                      -0.020739   
2     ...                   -2.286380                       0.010919   
3     ...                   -2.204285                       0.047435   
4     ...                   -2.116593                       0.084899   
...   ...                         ...                            ...   
1872  ...                   -0.002430                      -0.000467   
1873  ...                   -0.002173                      -0.000451   
1874  ...                   -0.001859                      -0.000471   
1875  ...                   -0.001557                      -0.000492   
1876  ...                   -0.001234                      -0.000514   

      Left Knee Internal/External Rotation  Left Knee Flexion/Extension  \
0                                -0.206231                    -0.000726   
1                                -0.084526                    -0.000119   
2                                 0.043672                    -0.000031   
3                             

In [16]:
dip_data=torch.load("/home/wanghao/桌面/Animation_human/data/dip_imu/1.pt")

In [37]:
poses=dip_data[0]
pose0=poses[0]

In [38]:
pose0=pose0.detach().numpy().tolist()

In [41]:
pose0[0]

[[0.9998874664306641, -0.012438775040209293, 0.008385127410292625],
 [0.012280386872589588, 0.999750018119812, 0.018683111295104027],
 [-0.008615425787866116, -0.01857803761959076, 0.9997903108596802]]

In [25]:
dip_data[1].shape

torch.Size([2755, 3])

In [1]:
import numpy as np

In [16]:
m1=np.array([[ -0.6203029,  0.0247216,  0.7839727],[0.0037154,  0.9995846, -0.0285809],[-0.7843536, -0.0148161, -0.6201370 ]])
m2=np.array([[1,0,0],[0,0.9938837,-0.1104317],[0,0.1104317,0.9938837]])
m = m1 @ m2

In [17]:
m

array([[-0.6203029 ,  0.11114583,  0.77644764],
       [ 0.0037154 ,  0.9903146 , -0.13879192],
       [-0.7843536 , -0.08320826, -0.61470789]])

In [2]:
#rotation matrices
def Rx(ang, in_radians = False):
    if in_radians == False:
        ang = np.radians(ang)

    Rot_Mat = np.array([
        [1, 0, 0],
        [0, np.cos(ang), -1*np.sin(ang)],
        [0, np.sin(ang),    np.cos(ang)]
    ])
    return Rot_Mat

def Ry(ang, in_radians = False):
    if in_radians == False:
        ang = np.radians(ang)

    Rot_Mat = np.array([
        [np.cos(ang), 0, np.sin(ang)],
        [0, 1, 0],
        [-1*np.sin(ang), 0, np.cos(ang)]
    ])
    return Rot_Mat

def Rz(ang, in_radians = False):
    if in_radians == False:
        ang = np.radians(ang)

    Rot_Mat = np.array([
        [np.cos(ang), -1*np.sin(ang), 0],
        [np.sin(ang), np.cos(ang), 0],
        [0, 0, 1]
    ])
    return Rot_Mat

In [110]:
m1= Ry(16.093358) @ Rx(-1.417120) @ Rz(0.474536)
m2= Ry(0) @ Rx(-6.340192) @ Rz(0)
m=np.linalg.inv(m2) @ m1 @ m2

In [111]:
Rotation.from_matrix(m).as_euler("ZXY",degrees=True)

array([ 2.59819607, -0.98603897, 15.95130773])

In [128]:
# m1= Rz(0.474536) @  Rx(-1.417120) @ Ry(16.093358)
# m2= Rz(0) @ Rx(-6.340192) @ Ry(0)

m1=Rotation.from_euler("YXZ",angles=[16.093358, -1.417120, 0.474536],degrees=True).as_matrix()
m2=Rotation.from_euler("YXZ",angles=[0, -6.340192, 0],degrees=True).as_matrix()
m= m2 @ m1 @ np.linalg.inv(m2)
Rotation.from_matrix(m).as_euler("YXZ",degrees=True)

array([16.08821332, -1.16862504, -1.28401294])

## kaishi

In [149]:
right_collar_rest_matrix=np.array([[0,-1,0],[1,0,0],[0,0,1]])
# right_collar_tosmpl_matrix=np.array([[0,1,0],[-1,0,0],[0,0,1]])
right_collar_pose_eluer=np.array([-11.218266,-8.709072,3.054929])
right_collar_pose_matrix=Rotation.from_euler("YXZ",right_collar_pose_eluer,degrees=True).as_matrix()

right_collar_pose_matrix_=np.linalg.inv(right_collar_rest_matrix) @ right_collar_pose_matrix @ right_collar_rest_matrix
Rotation.from_matrix(right_collar_pose_matrix_).as_euler("ZXY",degrees=True)

array([  8.87603997, -11.0872695 ,   1.33476167])